# Generated by Django 5.2.2 on 2025-06-07 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20250607_1918'),
    ]

    operations = [
    ]
